FROM ruby:3.4.9

WORKDIR /app

RUN apt-get update -qq && \
  apt-get install -y build-essential git libpq-dev postgresql-client

COPY Gemfile Gemfile.lock ./

RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0"]